sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t alurumuralikrishna9/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alurumuralikrishna9/docker-react npm run test -- --coverage
